In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/transactions.csv')

In [50]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6849346 entries, 0 to 6849345
Data columns (total 6 columns):
 #   Column       Dtype  
---  ------       -----  
 0   customer_id  int64  
 1   tr_datetime  object 
 2   mcc_code     int64  
 3   tr_type      int64  
 4   amount       float64
 5   term_id      object 
dtypes: float64(1), int64(3), object(2)
memory usage: 313.5+ MB


In [58]:
null_term_id_num = sum(df['term_id'].isna())

null_term_id_num / len(df) 

0.40371664681562297

In [54]:
df['term_id'].isna().any()

True

In [43]:
df = pd.read_parquet('data/client_id_map.parquet')

In [45]:
df.head()

,customer_id,encoded_client_id
0,10003267,0
1,10004871,1
2,10005741,2
3,10011328,3
4,10014090,4


In [46]:
len(df)

15000

In [44]:
set(df['encoded_client_id']) - set(range(len(df)))

set()

In [38]:
set(df['encoded_client_id'])

{0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [39]:
print(df['customer_id'])

0        10003267
1        10004871
2        10005741
3        10011328
4        10014090
           ...   
14995    99985917
14996    99988578
14997    99991245
14998      999976
14999    99999680
Name: customer_id, Length: 15000, dtype: object


In [40]:
for i in range(len(df)):
    print(df['customer_id'][i], df['encoded_client_id'][i])

10003267 0
10004871 1
10005741 2
10011328 3
10014090 4
10018695 5
10023080 6
10026296 7
10034284 8
1004170 9
10045498 10
10055880 11
10056437 12
10058557 13
10058778 14
10063530 15
10064386 16
10066310 17
10067396 18
10071732 19
10078312 20
10094853 21
10110730 22
10126330 23
1013552 24
1013842 25
1013875 26
10159490 27
10166707 28
10171705 29
10176170 30
10179649 31
1018926 32
10206133 33
1020634 34
10229977 35
10230827 36
1023983 37
10246339 38
10252148 39
10257726 40
10259614 41
10269885 42
10280886 43
10290561 44
1029705 45
10303548 46
10304262 47
10309206 48
10324267 49
10328342 50
10331386 51
10334951 52
10344936 53
10353051 54
10364899 55
10373501 56
10376120 57
10376412 58
10377190 59
10384721 60
10385103 61
10403039 62
104032 63
10403659 64
10413542 65
1044883 66
10464121 67
10467007 68
10469400 69
10476857 70
10482140 71
10490454 72
10493682 73
10499284 74
10506836 75
10519292 76
10521111 77
10524021 78
10565884 79
10574425 80
10589831 81
10596896 82
10598219 83
10600725 84
1

In [36]:
train_trx_df = pd.read_parquet('data/train_trx.parquet')

In [37]:
train_trx_df.head()

,customer_id,event_time,amount,mcc_code,tr_type,term_id,trx_count,target,encoded_client_id
0,10058778,"[23.35869212962963, 23.359502314814815, 36.498...","[13.420652589715486, -13.420652589715486, 14.6...","[2, 6, 3, 2, 2, 3, 2, 3, 2, 6, 6, 3, 10, 3, 2,...","[8, 13, 6, 3, 3, 23, 3, 11, 8, 19, 20, 6, 2, 6...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",142,1.0,14
1,10230827,"[0.25885416666666666, 1.5346412037037038, 1.65...","[13.015188216272872, -10.01949835204266, -9.76...","[3, 2, 5, 8, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 3, ...","[29, 3, 5, 5, 3, 3, 3, 4, 3, 3, 4, 3, 3, 4, 29...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",279,0.0,36
2,11681378,"[0.3015393518518519, 0.3589583333333333, 0.875...","[-8.41023807171957, -7.9242460340479255, -9.91...","[4, 7, 2, 2, 11, 5, 7, 6, 2, 7, 7, 3, 6, 7, 7,...","[4, 2, 27, 28, 2, 5, 2, 13, 3, 2, 2, 9, 13, 2,...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",881,1.0,277
3,14123285,"[15.489155092592593, 21.68777777777778, 23.612...","[12.792045221523114, 12.216683253401992, -10.7...","[3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 3, 3, 2, 2, 2, ...","[11, 9, 16, 25, 25, 16, 11, 6, 16, 25, 11, 17,...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",1051,0.0,644
4,16536678,"[75.40552083333333, 75.59731481481481, 83.5602...","[14.336942434053569, -9.326395693771916, -9.32...","[2, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4, 4, 4, 4, ...","[8, 4, 4, 4, 4, 8, 4, 4, 4, 8, 4, 4, 4, 4, 4, ...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",128,0.0,1041


In [43]:
train__coles_item_ids = {el for seq in train_trx_df['mcc_code'] for el in seq}

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185}


In [44]:
train__coles_item_ids == set(range(2, 186))

True

In [45]:
test_trx_df = pd.read_parquet('data/test_trx.parquet')
test_trx_df.head()

,customer_id,event_time,amount,mcc_code,tr_type,term_id,trx_count,target,encoded_client_id
0,24227698,"[2.6528125, 7.377939814814815, 16.875011574074...","[-10.424948618947251, -11.811220643640558, -11...","[2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, ...","[3, 3, 3, 3, 8, 3, 4, 8, 3, 3, 8, 3, 3, 8, 8, ...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",235,1,2293
1,29097966,"[-0.125, 0.2008449074074074, 1.875, 1.875, 3.2...","[-8.79882449483086, -7.024613442631785, -9.204...","[8, 4, 8, 5, 4, 2, 8, 9, 2, 4, 4, 8, 26, 2, 5,...","[5, 4, 5, 5, 4, 3, 5, 5, 3, 4, 4, 5, 2, 3, 2, ...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",1255,1,3110
2,46431440,"[12.289259259259259, 14.403055555555556, 14.45...","[10.974982295004144, -12.227733055882192, -8.4...","[2, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 4, 2, 2, ...","[8, 3, 18, 3, 4, 3, 8, 4, 3, 4, 18, 3, 4, 3, 1...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",144,0,5946
3,48119333,"[0.875, 1.116886574074074, 1.4504398148148148,...","[-8.969759419013014, 11.118080809668006, 11.62...","[49, 3, 3, 2, 8, 3, 4, 8, 8, 76, 5, 4, 4, 4, 5...","[10, 6, 9, 16, 5, 6, 4, 5, 5, 5, 5, 4, 4, 4, 5...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",632,1,6233
4,50796712,"[1.0409143518518518, 1.2863194444444446, 1.293...","[-10.722058283317635, -7.773670190197818, -9.3...","[8, 5, 5, 5, 2, 5, 9, 5, 4, 5, 5, 4, 5, 5, 5, ...","[5, 2, 5, 2, 3, 5, 5, 5, 4, 5, 5, 4, 5, 5, 5, ...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",455,1,6710


In [47]:
test__coles_item_ids = {el for seq in test_trx_df['mcc_code'] for el in seq}

In [49]:
test__coles_item_ids == train__coles_item_ids

False

In [55]:
# <= is a `is_subset` operator
test__coles_item_ids <= train__coles_item_ids

True

In [46]:
test_trx_df['encoded_client_id'].unique()

array([ 2293,  3110,  5946,  6233,  6710,  8867,  9877, 10575, 13190,
       13802, 14110,   184,  1552,  1952,  2745,  2865,  3153,  4574,
        6555,  8891,  9712, 11250, 11770, 12554,   595,  3868,  4703,
        5250,  6825,  7888,  8111, 10597, 10813, 10906, 11000, 12639,
       12968, 13238, 13726,   613,  3677,  3712,  4349,  5399,  7747,
        9939, 10831,   351,   751,  2433,  2815,  2948,  3731,  4085,
        4779,  5165,  6049,  6101,  6192,  6681,  7712,  9586,  9695,
       11484, 11919, 12309, 12484, 13005, 13461, 13681,   833,  3956,
        4541,  4616,  7956,  8719,  9708, 11007, 11057, 13260,  3055,
        3760,  3830,  5136,  9729, 12412, 13476, 14886,   592,   992,
        1066,  2793,  2894,  4398,  6299,  9802, 10492, 10818, 13710,
        1785,  2522,  2867,  3563,  4232,  4483,  5438,  6119,  6169,
        6276,  7475,  8055,  8130,  8412,  8429, 13932,   811,  2749,
        2770,  3345,  3642,  5154,  6376,  6934,  6970,  7379,  7926,
        8275, 10564,

In [3]:
import torch

In [4]:
item_id2train_graph_id = torch.load('./data/graphs/weighted/item_id2train_graph_id.pt')

In [5]:
item_id2train_graph_id

tensor([    0,     0, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167,
        14168, 14169, 14170, 14171, 14172, 14173, 14174, 14175, 14176, 14177,
        14178, 14179, 14180, 14181, 14182, 14183, 14184, 14185, 14186, 14187,
        14188, 14189, 14190, 14191, 14192, 14193, 14194, 14195, 14196, 14197,
        14198, 14199, 14200, 14201, 14202, 14203, 14204, 14205, 14206, 14207,
        14208, 14209, 14210, 14211, 14212, 14213, 14214, 14215, 14216, 14217,
        14218, 14219, 14220, 14221, 14222, 14223, 14224, 14225, 14226, 14227,
        14228, 14229, 14230, 14231, 14232, 14233, 14234, 14235, 14236, 14237,
        14238, 14239, 14240, 14241, 14242, 14243, 14244, 14245, 14246, 14247,
        14248, 14249, 14250, 14251, 14252, 14253, 14254, 14255, 14256, 14257,
        14258, 14259, 14260, 14261, 14262, 14263, 14264, 14265, 14266, 14267,
        14268, 14269, 14270, 14271, 14272, 14273, 14274, 14275, 14276, 14277,
        14278, 14279, 14280, 14281, 14282, 14283, 14284, 14285, 

In [6]:
len(item_id2train_graph_id)

186

In [7]:
item_id2train_graph_id

tensor([    0,     0, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167,
        14168, 14169, 14170, 14171, 14172, 14173, 14174, 14175, 14176, 14177,
        14178, 14179, 14180, 14181, 14182, 14183, 14184, 14185, 14186, 14187,
        14188, 14189, 14190, 14191, 14192, 14193, 14194, 14195, 14196, 14197,
        14198, 14199, 14200, 14201, 14202, 14203, 14204, 14205, 14206, 14207,
        14208, 14209, 14210, 14211, 14212, 14213, 14214, 14215, 14216, 14217,
        14218, 14219, 14220, 14221, 14222, 14223, 14224, 14225, 14226, 14227,
        14228, 14229, 14230, 14231, 14232, 14233, 14234, 14235, 14236, 14237,
        14238, 14239, 14240, 14241, 14242, 14243, 14244, 14245, 14246, 14247,
        14248, 14249, 14250, 14251, 14252, 14253, 14254, 14255, 14256, 14257,
        14258, 14259, 14260, 14261, 14262, 14263, 14264, 14265, 14266, 14267,
        14268, 14269, 14270, 14271, 14272, 14273, 14274, 14275, 14276, 14277,
        14278, 14279, 14280, 14281, 14282, 14283, 14284, 14285, 

In [8]:
unique_elements = item_id2train_graph_id.unique()
unique_elements

tensor([    0, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167, 14168,
        14169, 14170, 14171, 14172, 14173, 14174, 14175, 14176, 14177, 14178,
        14179, 14180, 14181, 14182, 14183, 14184, 14185, 14186, 14187, 14188,
        14189, 14190, 14191, 14192, 14193, 14194, 14195, 14196, 14197, 14198,
        14199, 14200, 14201, 14202, 14203, 14204, 14205, 14206, 14207, 14208,
        14209, 14210, 14211, 14212, 14213, 14214, 14215, 14216, 14217, 14218,
        14219, 14220, 14221, 14222, 14223, 14224, 14225, 14226, 14227, 14228,
        14229, 14230, 14231, 14232, 14233, 14234, 14235, 14236, 14237, 14238,
        14239, 14240, 14241, 14242, 14243, 14244, 14245, 14246, 14247, 14248,
        14249, 14250, 14251, 14252, 14253, 14254, 14255, 14256, 14257, 14258,
        14259, 14260, 14261, 14262, 14263, 14264, 14265, 14266, 14267, 14268,
        14269, 14270, 14271, 14272, 14273, 14274, 14275, 14276, 14277, 14278,
        14279, 14280, 14281, 14282, 14283, 14284, 14285, 14286, 

In [10]:
torch.equal(
    item_id2train_graph_id[len(item_id2train_graph_id)-len(unique_elements):],
    unique_elements
)

True

In [13]:
client_id2train_graph_id = torch.load('./data/graphs/weighted/client_id2train_graph_id.pt')

In [14]:
len(client_id2train_graph_id)

15000

In [29]:
set(map(int, client_id2train_graph_id.unique())) == set(range(14160))

True

In [10]:
item_id2full_graph_id = torch.load('./data/graphs/weighted/item_id2full_graph_id.pt')

In [11]:
len(item_id2full_graph_id)

185

In [23]:
item_id2full_graph_id

NameError: name 'item_id2full_graph_id' is not defined

In [85]:
client_id2full_graph_id = torch.load('./data/graphs/weighted/client_id2full_graph_id.pt')

In [87]:
len(client_id2full_graph_id)

15000

In [88]:
client_id2full_graph_id

tensor([    0,     1,     2,  ..., 14997, 14998, 14999])

In [89]:
client_id2full_graph_id.unique()

tensor([    0,     1,     2,  ..., 14997, 14998, 14999])

In [93]:
{int(el) for el in client_id2full_graph_id} == set(range(len(client_id2train_graph_id)))

True

In [34]:
client_id2train_graph_id[df['encoded_client_id'].unique()]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [17]:
%cd ..

/path/to/repo/Documents/my-coles-gnn-experimetns


/path/to/repo/.local/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [18]:
from ptls_extension_2024_research.graphs.graph import ClientItemGraph, ClientItemGraphFull


/path/to/repo/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


ModuleNotFoundError: No module named '_lzma'

In [ ]:
graph_file_path = 'data/graphs/weighted/train_graph.bin'
client_item_graph = ClientItemGraphFull.from_graph_file(graph_file_path, 'cpu')

In [ ]:
print(client_item_graph.g.nodes())


In [ ]:
len(client_item_graph.g.nodes())


In [12]:
import pandas as pd

In [16]:
df = pd.read_csv('data/transactions.csv')
df.head()

,customer_id,tr_datetime,mcc_code,tr_type,amount,term_id
0,39026145,0 10:23:26,4814,1030,-2245.92,NaN
1,39026145,1 10:19:29,6011,7010,56147.89,NaN
2,39026145,1 10:20:56,4829,2330,-56147.89,NaN
3,39026145,1 10:39:54,5499,1010,-1392.47,NaN
4,39026145,2 15:33:42,5499,1010,-920.83,NaN


In [17]:
df['mcc_code'].unique()

array([4814, 6011, 4829, 5499, 5541, 5200, 5732, 6010, 5331, 5912, 5411,
       5812, 6012, 5719, 5722, 5621, 5814, 5921, 5941, 5691, 5813, 5211,
       4812, 5945, 5983, 5999, 5943, 5533, 6300, 7832, 8099, 5992, 3501,
       6536, 7997, 5641, 4722, 5661, 5651, 7011, 5699, 5942, 7298, 7999,
       5712, 5511, 5422, 5399, 4900, 7538, 5949, 5977, 5948, 5631, 5311,
       5462, 4112, 8999, 8021, 5714, 5251, 4789, 7542, 5947, 3000, 8043,
       5944, 5734, 5611, 5532, 4816, 7311, 5655, 6051, 7994, 5995, 5309,
       5964, 8299, 8244, 4111, 4511, 9399, 5441, 7922, 5261, 7699, 7995,
       7629, 5816, 5735, 5039, 5300, 5199, 4121, 5065, 7399, 7299, 8011,
       7230, 9222, 5946, 5131, 5994, 5231, 8071, 5094, 5047, 5072, 7210,
       5976, 5045, 7932, 4215, 5542, 5099, 5713, 4899, 7933, 5681, 5193,
       1711, 6211, 8398, 5599, 5993, 8062, 5169, 4214, 5733, 5013, 7221,
       5571, 7993, 5971, 5968, 7372, 5074, 5044, 5811, 5111, 8641, 7512,
       7523, 9311, 8220, 7991, 7996, 4784, 5931, 78

In [18]:
len(df['mcc_code'].unique())

184

In [19]:
ptls_train_df = pd.read_parquet('data/train_trx.parquet/')

In [20]:
ptls_train_df.head()

,customer_id,event_time,amount,mcc_code,tr_type,term_id,trx_count,target
0,10058778,"[23.35869212962963, 23.359502314814815, 36.498...","[13.420652589715486, -13.420652589715486, 14.6...","[2, 6, 3, 2, 2, 3, 2, 3, 2, 6, 6, 3, 10, 3, 2,...","[8, 13, 6, 3, 3, 23, 3, 11, 8, 19, 20, 6, 2, 6...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",142,1.0
1,10230827,"[0.25885416666666666, 1.5346412037037038, 1.65...","[13.015188216272872, -10.01949835204266, -9.76...","[3, 2, 5, 8, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 3, ...","[29, 3, 5, 5, 3, 3, 3, 4, 3, 3, 4, 3, 3, 4, 29...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",279,0.0
2,11681378,"[0.3015393518518519, 0.3589583333333333, 0.875...","[-8.41023807171957, -7.9242460340479255, -9.91...","[4, 7, 2, 2, 11, 5, 7, 6, 2, 7, 7, 3, 6, 7, 7,...","[4, 2, 27, 28, 2, 5, 2, 13, 3, 2, 2, 9, 13, 2,...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",881,1.0
3,14123285,"[15.489155092592593, 21.68777777777778, 23.612...","[12.792045221523114, 12.216683253401992, -10.7...","[3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 3, 3, 2, 2, 2, ...","[11, 9, 16, 25, 25, 16, 11, 6, 16, 25, 11, 17,...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",1051,0.0
4,16536678,"[75.40552083333333, 75.59731481481481, 83.5602...","[14.336942434053569, -9.326395693771916, -9.32...","[2, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4, 4, 4, 4, ...","[8, 4, 4, 4, 4, 8, 4, 4, 4, 8, 4, 4, 4, 4, 4, ...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",128,0.0


In [23]:
mcc_ids = {el for arr in ptls_train_df['mcc_code'] for el in arr}

In [25]:
print(mcc_ids)

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185}


In [26]:
?df.to_parquet

Signature:
df.to_parquet(
    path: 'FilePath | WriteBuffer[bytes] | None' = None,
    engine: "Literal['auto', 'pyarrow', 'fastparquet']" = 'auto',
    compression: 'str | None' = 'snappy',
    index: 'bool | None' = None,
    partition_cols: 'list[str] | None' = None,
    storage_options: 'StorageOptions | None' = None,
    **kwargs,
) -> 'bytes | None'
Docstring:
Write a DataFrame to the binary parquet format.

This function writes the dataframe as a `parquet file
<https://parquet.apache.org/>`_. You can choose different parquet
backends, and have the option of compression. See
:ref:`the user guide <io.parquet>` for more details.

Parameters
----------
path : str, path object, file-like object, or None, default None
    String, path object (implementing ``os.PathLike[str]``), or file-like
    object implementing a binary ``write()`` function. If None, the result is
    returned as bytes. If a string or path, it will be used as Root Directory
    path when writing a partitioned datas

In [28]:
import pickle

with open('data/train_trx.parquet', 'rb') as f:
    data = pickle.load(f)

In [30]:
type(data)

list

In [31]:
data[0]

{'target': 1,
 'customer_id': 22899,
 'feature_arrays': {'mcc_code': array([ 3,  3,  1,  1,  2,  1,  1,  3,  1,  3,  2,  1,  2,  3,  1,  2,  7,
          8,  3,  1,  1,  1,  1,  3,  3,  2,  7,  2,  1,  3,  1,  2,  5,  5,
          6,  3,  1,  1,  5,  2,  5,  1,  5,  2,  1,  1,  1,  2,  5,  1,  3,
          3,  2,  2,  1,  3,  1,  6,  1,  3,  1,  1,  3,  3,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  3,  1,  3,  6,  1,  5,  2,  1,  3,  3,  4,  1,
          1,  4,  7,  6,  1,  1,  6,  1,  5,  6,  1,  1,  5,  5,  6,  7,  3,
          2,  7,  1,  5,  5, 49,  3,  1,  6,  2,  3,  1,  1,  1,  2,  2,  1,
          2,  1,  1,  1,  5,  3,  1,  7,  7,  6,  3,  2,  1,  1,  1,  3,  1,
          3,  1,  1,  1,  1,  1,  5,  5,  2,  6,  5,  1,  2,  3,  3,  1,  3,
          3,  2,  1,  3,  3,  1,  2,  1,  1,  3,  3,  1,  5,  4,  1,  1,  3,
          1,  1,  5,  5,  1,  3,  3,  3,  2,  6,  1,  1,  3,  6,  1,  3,  1,
          1,  1,  6,  2,  3,  1,  3,  1,  5,  5,  1,  1,  1,  1,  6,  1,  3,
         

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('data/transactions.csv')
df.head()

,customer_id,tr_datetime,mcc_code,tr_type,amount,term_id
0,39026145,0 10:23:26,4814,1030,-2245.92,NaN
1,39026145,1 10:19:29,6011,7010,56147.89,NaN
2,39026145,1 10:20:56,4829,2330,-56147.89,NaN
3,39026145,1 10:39:54,5499,1010,-1392.47,NaN
4,39026145,2 15:33:42,5499,1010,-920.83,NaN


In [39]:
df['mcc_code'].head()

0    4814
1    6011
2    4829
3    5499
4    5499
Name: mcc_code, dtype: int64

In [40]:
item_map = pd.read_csv('data/mcc_code_mapping.csv')
item_map.head()

,_orig_mcc_code,mcc_code
0,6011,2
1,6010,3
2,4814,4
3,5411,5
4,4829,6


In [41]:
df = df.rename(columns={'mcc_code': '_orig_mcc_code'})
df['_orig_mcc_code'] = df['_orig_mcc_code'].fillna("#EMPTY")

In [42]:
df = df.merge(item_map, on='_orig_mcc_code', how='left')
df.head()

,customer_id,tr_datetime,_orig_mcc_code,tr_type,amount,term_id,mcc_code
0,39026145,0 10:23:26,4814,1030,-2245.92,NaN,4
1,39026145,1 10:19:29,6011,7010,56147.89,NaN,2
2,39026145,1 10:20:56,4829,2330,-56147.89,NaN,6
3,39026145,1 10:39:54,5499,1010,-1392.47,NaN,7
4,39026145,2 15:33:42,5499,1010,-920.83,NaN,7


In [43]:
df = df.drop(columns = ['_orig_mcc_code'])
df.head()

,customer_id,tr_datetime,tr_type,amount,term_id,mcc_code
0,39026145,0 10:23:26,1030,-2245.92,NaN,4
1,39026145,1 10:19:29,7010,56147.89,NaN,2
2,39026145,1 10:20:56,2330,-56147.89,NaN,6
3,39026145,1 10:39:54,1010,-1392.47,NaN,7
4,39026145,2 15:33:42,1010,-920.83,NaN,7


In [67]:
mask_ids = {0, 7179, 10258, 8723, 31, 1583, 10295, 9793, 70, 13896, 5706, 10832, 10331, 5214, 10864, 5746, 5242, 6267, 3707, 1671, 3209, 3219, 11415, 162, 6842, 3259, 6334, 3783, 13010, 3802, 3291, 1761, 2788, 2804, 12026, 4352, 258, 5381, 2826, 14094, 7951, 4910, 314, 3386, 8506, 7998, 841, 2891, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167, 14168, 14169, 14170, 14171, 14172, 14173, 7518, 14174, 14175, 14176, 14177, 14178, 14179, 14180, 14182, 14183, 14184, 14185, 14187, 14188, 14189, 14190, 14191, 14192, 14193, 6514, 14194, 14195, 14196, 10614, 14197, 14198, 14199, 14200, 14201, 14202, 14203, 14204, 14205, 14206, 14209, 14210, 14211, 14212, 14213, 14214, 14217, 14218, 14219, 14220, 14221, 5008, 14224, 14226, 14228, 14233, 14234, 4508, 14237, 14238, 416, 14240, 14241, 14242, 5547, 8621, 14254, 14256, 14261, 4537, 14272, 14280, 14287, 7633, 14289, 12244, 4056, 9178, 14298, 14299, 10207, 4579, 14310, 12779, 5108}
changed_ids = {0, 14336, 13831, 7179, 10258, 8723, 7193, 13338, 31, 1583, 10295, 9793, 10821, 70, 13896, 5706, 10832, 2139, 92, 10331, 5214, 6254, 4207, 10864, 5746, 12409, 5242, 6267, 3707, 9340, 9850, 9853, 13440, 13945, 5763, 13956, 1671, 3209, 650, 7817, 3219, 1684, 3735, 11415, 2718, 162, 1186, 9382, 9899, 2225, 10936, 6842, 3259, 6334, 4293, 3783, 4811, 13010, 3802, 3291, 9434, 1249, 1761, 2788, 14215, 10993, 2804, 9976, 12026, 4352, 258, 13058, 11524, 1285, 5381, 12036, 2826, 14094, 7951, 1811, 14217, 1834, 10538, 813, 4910, 10032, 6456, 12600, 314, 3386, 8506, 7998, 11587, 327, 841, 3401, 2891, 14154, 336, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167, 14168, 13658, 14169, 14170, 14171, 7518, 14172, 14173, 14174, 14175, 14176, 14177, 14178, 14179, 14180, 12136, 14182, 14183, 14184, 14185, 12141, 8558, 14186, 14187, 14188, 6514, 6003, 14189, 14190, 10614, 14191, 14192, 14193, 14194, 14195, 14196, 14197, 14198, 14199, 14200, 14201, 3970, 14202, 14203, 14204, 14205, 14206, 14207, 14208, 14209, 14210, 14211, 14212, 14213, 14214, 5008, 14216, 11666, 14218, 14219, 14220, 14221, 14222, 14223, 13209, 3994, 14225, 4508, 14226, 14229, 8095, 416, 14228, 14233, 14234, 14237, 14238, 14239, 14240, 14241, 14242, 14244, 5547, 14245, 8621, 14251, 14252, 14254, 14256, 14260, 14261, 4537, 10681, 14266, 14267, 14271, 14272, 14276, 2503, 9159, 14280, 14224, 14287, 7633, 14289, 3540, 12244, 14293, 4056, 9178, 14298, 14299, 14301, 10207, 14305, 4579, 14310, 12779, 8179, 5108, 10228, 14332}


In [68]:
len(mask_ids)

141

In [69]:
len(changed_ids)

229

In [70]:
changed_ids - mask_ids

{92,
 327,
 336,
 650,
 813,
 1186,
 1249,
 1285,
 1684,
 1811,
 1834,
 2139,
 2225,
 2503,
 2718,
 3401,
 3540,
 3735,
 3970,
 3994,
 4207,
 4293,
 4811,
 5763,
 6003,
 6254,
 6456,
 7193,
 7817,
 8095,
 8179,
 8558,
 9159,
 9340,
 9382,
 9434,
 9850,
 9853,
 9899,
 9976,
 10032,
 10228,
 10538,
 10681,
 10821,
 10936,
 10993,
 11524,
 11587,
 11666,
 12036,
 12136,
 12141,
 12409,
 12600,
 13058,
 13209,
 13338,
 13440,
 13658,
 13831,
 13945,
 13956,
 14154,
 14186,
 14207,
 14208,
 14215,
 14216,
 14222,
 14223,
 14225,
 14229,
 14239,
 14244,
 14245,
 14251,
 14252,
 14260,
 14266,
 14267,
 14271,
 14276,
 14293,
 14301,
 14305,
 14332,
 14336}

In [2]:
%cd ..

/path/to/repo/Documents/my-coles-gnn-experimetns


In [38]:
from ptls_extension_2024_research.graphs.graph import ClientItemGraph, ClientItemGraphFull

In [39]:
graph_1 = ClientItemGraphFull.from_graph_file('./scenario_gender/data/graphs/weighted/train_graph.bin', device_name = 'cpu')
graph_1

ClientItemGraphFull(g=Graph(num_nodes=14344, num_edges=573328,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'weight': Scheme(shape=(), dtype=torch.float32)}), device_name='cpu')

In [40]:
graph_2 = ClientItemGraph.from_graph_file('./scenario_gender/data/graphs/weighted/train_graph.bin', device_name='cpu')
graph_2

ClientItemGraph(g=Graph(num_nodes=14344, num_edges=573328,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'weight': Scheme(shape=(), dtype=torch.float32)}), device_name='cpu')

In [55]:
graph_2.g.number_of_nodes() == graph_1.g.number_of_nodes()

True

In [59]:
n_nodes = graph_2.g.number_of_nodes()
n_nodes

14344

In [57]:
graph_1.g.ndata['_ID']

tensor([    0,     1,     2,  ..., 14341, 14342, 14343])

In [56]:
graph_2.g.ndata['_ID']

tensor([    0,     1,     2,  ..., 15181, 15182, 15183])

In [50]:
torch.all(graph_1.g.ndata['_ID'] == torch.arange(0, n_nodes))


tensor(True)

In [49]:
torch.all(graph_2.g.ndata['_ID'] == torch.arange(0, n_nodes))

tensor(False)

True

In [37]:
for expected_i, i in enumerate(graph_2.g.ndata['_ID']):
    i = int(i)
    if i != expected_i:
        print(i, expected_i)

10 9
11 10
12 11
13 12
14 13
15 14
16 15
18 16
19 17
20 18
21 19
22 20
23 21
24 22
25 23
27 24
28 25
29 26
30 27
31 28
33 29
34 30
35 31
36 32
37 33
38 34
39 35
40 36
41 37
42 38
43 39
44 40
45 41
46 42
47 43
48 44
49 45
50 46
51 47
52 48
53 49
54 50
55 51
57 52
58 53
59 54
60 55
61 56
62 57
63 58
64 59
65 60
66 61
67 62
68 63
69 64
70 65
71 66
72 67
73 68
74 69
75 70
76 71
77 72
78 73
79 74
80 75
81 76
83 77
84 78
85 79
86 80
88 81
89 82
90 83
91 84
92 85
93 86
95 87
96 88
97 89
98 90
99 91
100 92
101 93
102 94
103 95
104 96
105 97
106 98
107 99
108 100
109 101
110 102
111 103
112 104
113 105
114 106
115 107
117 108
118 109
119 110
120 111
121 112
122 113
123 114
124 115
125 116
126 117
127 118
128 119
129 120
130 121
131 122
132 123
133 124
134 125
135 126
136 127
137 128
139 129
140 130
141 131
142 132
144 133
145 134
146 135
147 136
148 137
149 138
150 139
151 140
152 141
153 142
154 143
155 144
156 145
157 146
158 147
159 148
160 149
161 150
162 151
163 152
164 153
165 154
166 155

In [35]:
import torch


In [4]:
from ptls_extension_2024_research.frames.gnn.gnn_module import ColesBatchToSubgraphConverter

In [63]:
from ptls_extension_2024_research.graphs.graph import ClientItemGraph

In [1]:
!ls data/graphs/weighted/full_graph.bin


adj_embs.pt
adj_feats__cosine__similarities.pickle
bins__adj_embs-cosine_similarity-deleted_empty_bins.pickle
bins__adj_embs-cosine_similarity-no_postprocessing__backup.pickle
bins__adj_embs-cosine_similarity-no_postprocessing.pickle
bins__adj_embs-tuple_tuple_set-cosine_similarity-no_postprocessing.pickle
bins__adj_embs-tuple_tuple_tuple-cosine_similarity-no_postprocessing.pickle
bins__adj_embs-unordered-cosine_similarity-no_postprocessing.pickle
client_id2full_graph_id.pt
client_id2train_graph_id__dict.pt
client_id2train_graph_id.pt
full_graph.bin
gender_graph__05_09_2024.zip
item_id2full_graph_id.pt
item_id2train_graph_id.pt
train_graph.bin
train_graph.gml
train_graph_id2client_id__dict.pt


In [2]:
import dgl

/path/to/repo/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
(train_g,), _ = dgl.load_graphs('data/graphs/weighted/train_graph.bin')

In [4]:
(full_g,), _ = dgl.load_graphs('data/graphs/weighted/full_graph.bin')

In [7]:
len(train_g.nodes())

14344

In [9]:
len(train_g.edges()[0])

573328

In [10]:
len(full_g.nodes())

15184

In [11]:
len(full_g.edges()[0])

608214

In [16]:
import numpy as np
from typing import List, Set, Optional

# The original (non-optimized) version
def create_bins_for_user_original(values: List[int], 
                                  n_bins: int, 
                                  exclude_id: Optional[int] = None) -> List[Set[int]]:
    indexed_values = tuple((idx, val) for idx, val in enumerate(values) if idx != exclude_id)

    min_val, max_val = min(indexed_values, key=lambda x: x[1])[1], max(indexed_values, key=lambda x: x[1])[1]
    bin_size = (max_val - min_val) / n_bins
    
    bins = [set() for _ in range(n_bins)]
    
    eps = 1e-6
    for idx, val in indexed_values:
        bin_idx = int((val - min_val) // (bin_size + eps))
        if bin_idx == n_bins:
            bin_idx -= 1
        bins[bin_idx].add(idx)
        
    return bins

# The optimized version
def create_bins_for_user_optimized(values: np.ndarray, 
                                   n_bins: int, 
                                   exclude_id: Optional[int] = None) -> List[Set[int]]:
    if exclude_id is not None:
        mask = np.arange(values.shape[0]) != exclude_id
        indexed_values = np.arange(values.shape[0])[mask]
        values = values[mask]
    else:
        indexed_values = np.arange(values.shape[0])

    min_val, max_val = np.min(values), np.max(values)
    bin_size = (max_val - min_val) / n_bins

    bins = [set() for _ in range(n_bins)]
    
    eps = 1e-6
    bin_indices = np.floor((values - min_val) / (bin_size + eps)).astype(int)
    bin_indices = np.clip(bin_indices, 0, n_bins - 1)
    
    for idx, bin_idx in zip(indexed_values, bin_indices):
        bins[bin_idx].add(idx)
        
    return bins

# Test cases
def test_equal_output():
    # Test case 1: Simple range of values
    values = [1, 2, 3, 4, 5, 6]
    n_bins = 3
    exclude_id = None
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

def test_exclude_id():
    # Test case 2: Exclude an ID
    values = [1, 5, 10, 20]
    n_bins = 2
    exclude_id = 1  # Exclude the element with index 1 (value 5)
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

def test_all_values_same():
    # Test case 3: All values are the same
    values = [10, 10, 10, 10]
    n_bins = 2
    exclude_id = None
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

def test_large_range_of_values():
    # Test case 4: Large range of values
    values = [1, 10, 20, 100, 200, 500, 1000]
    n_bins = 5
    exclude_id = None
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

def test_non_uniform_distribution():
    # Test case 5: Non-uniformly distributed values
    values = [1, 2, 2, 3, 100, 101]
    n_bins = 3
    exclude_id = None
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

def test_exclude_id_out_of_bounds():
    # Test case 6: Exclude an ID that is out of bounds (should do nothing)
    values = [5, 15, 25, 35]
    n_bins = 2
    exclude_id = 10  # Non-existent ID
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

# You can run these tests with pytest by simply running the command:
# pytest <name_of_test_file>.py


In [17]:
test_equal_output()


test_exclude_id()


test_all_values_same()


test_large_range_of_values()


test_non_uniform_distribution()


test_exclude_id_out_of_bounds()



In [16]:
import torch

client_id2train_graph_id = torch.load('./data/graphs/weighted/client_id2train_graph_id.pt')

In [17]:
max(client_id2train_graph_id)

tensor(16000)

In [19]:
# for i in client_id2train_graph_id:
#     print(int(i))